// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentSync_Ping_FullMethodName                 = "/proto.AgentSync/Ping"
	AgentSync_SyncState_FullMethodName            = "/proto.AgentSync/SyncState"
	AgentSync_StreamInference_FullMethodName      = "/proto.AgentSync/StreamInference"
	AgentSync_RemoteExecute_FullMethodName        = "/proto.AgentSync/RemoteExecute"
	AgentSync_CreateUser_FullMethodName           = "/proto.AgentSync/CreateUser"
	AgentSync_ChangePassword_FullMethodName       = "/proto.AgentSync/ChangePassword"
	AgentSync_ManageGroup_FullMethodName          = "/proto.AgentSync/ManageGroup"
	AgentSync_ListUsers_FullMethodName            = "/proto.AgentSync/ListUsers"
	AgentSync_SyncUsers_FullMethodName            = "/proto.AgentSync/SyncUsers"
	AgentSync_GetProcessDirectory_FullMethodName  = "/proto.AgentSync/GetProcessDirectory"
	AgentSync_GetPortBindings_FullMethodName      = "/proto.AgentSync/GetPortBindings"
	AgentSync_TeleportAgent_FullMethodName        = "/proto.AgentSync/TeleportAgent"
	AgentSync_TracePedigree_FullMethodName        = "/proto.AgentSync/TracePedigree"
	AgentSync_ProposeSwarmMutation_FullMethodName = "/proto.AgentSync/ProposeSwarmMutation"
	AgentSync_QuerySwarmLedger_FullMethodName     = "/proto.AgentSync/QuerySwarmLedger"
	AgentSync_TimeTravelOverride_FullMethodName   = "/proto.AgentSync/TimeTravelOverride"
	AgentSync_ForensicAudit_FullMethodName        = "/proto.AgentSync/ForensicAudit"
)

// AgentSyncClient is the client API for AgentSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentSyncClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	SyncState(ctx context.Context, in *StatePayload, opts ...grpc.CallOption) (*SyncAck, error)
	StreamInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InferenceChunk], error)
	RemoteExecute(ctx context.Context, in *CommandPayload, opts ...grpc.CallOption) (*CommandResult, error)
	// User Maintenance & Synchronization RPCs
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ManageGroup(ctx context.Context, in *ManageGroupRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ListUsers(ctx context.Context, in *UserDirectoryRequest, opts ...grpc.CallOption) (*UserDirectoryResponse, error)
	SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// Process & Port Monitoring RPCs
	GetProcessDirectory(ctx context.Context, in *ProcessDirectoryRequest, opts ...grpc.CallOption) (*ProcessDirectoryResponse, error)
	GetPortBindings(ctx context.Context, in *PortBindingsRequest, opts ...grpc.CallOption) (*PortBindingsResponse, error)
	// High-Speed Agent Migration (Virtual Travel) RPC
	TeleportAgent(ctx context.Context, in *TeleportRequest, opts ...grpc.CallOption) (*TeleportResponse, error)
	// Agent Pedigree & 7-Layer Swarm Cooperation RPC
	TracePedigree(ctx context.Context, in *PedigreeRequest, opts ...grpc.CallOption) (*PedigreeResponse, error)
	// Agent Ticketing, Relational Memory, and Immutable Ledger RPCs
	ProposeSwarmMutation(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	QuerySwarmLedger(ctx context.Context, in *LedgerQueryRequest, opts ...grpc.CallOption) (*LedgerQueryResponse, error)
	// Jetweb Time Machine & Forensic Decision Accounting RPCs
	TimeTravelOverride(ctx context.Context, in *TimeTravelRequest, opts ...grpc.CallOption) (*TimeTravelResponse, error)
	ForensicAudit(ctx context.Context, in *ForensicRequest, opts ...grpc.CallOption) (*ForensicResponse, error)
}

type agentSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentSyncClient(cc grpc.ClientConnInterface) AgentSyncClient {
	return &agentSyncClient{cc}
}

func (c *agentSyncClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentSync_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) SyncState(ctx context.Context, in *StatePayload, opts ...grpc.CallOption) (*SyncAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAck)
	err := c.cc.Invoke(ctx, AgentSync_SyncState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) StreamInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InferenceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentSync_ServiceDesc.Streams[0], AgentSync_StreamInference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferenceRequest, InferenceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentSync_StreamInferenceClient = grpc.ServerStreamingClient[InferenceChunk]

func (c *agentSyncClient) RemoteExecute(ctx context.Context, in *CommandPayload, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, AgentSync_RemoteExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, AgentSync_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, AgentSync_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) ManageGroup(ctx context.Context, in *ManageGroupRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, AgentSync_ManageGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) ListUsers(ctx context.Context, in *UserDirectoryRequest, opts ...grpc.CallOption) (*UserDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDirectoryResponse)
	err := c.cc.Invoke(ctx, AgentSync_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, AgentSync_SyncUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) GetProcessDirectory(ctx context.Context, in *ProcessDirectoryRequest, opts ...grpc.CallOption) (*ProcessDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDirectoryResponse)
	err := c.cc.Invoke(ctx, AgentSync_GetProcessDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) GetPortBindings(ctx context.Context, in *PortBindingsRequest, opts ...grpc.CallOption) (*PortBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortBindingsResponse)
	err := c.cc.Invoke(ctx, AgentSync_GetPortBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) TeleportAgent(ctx context.Context, in *TeleportRequest, opts ...grpc.CallOption) (*TeleportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeleportResponse)
	err := c.cc.Invoke(ctx, AgentSync_TeleportAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) TracePedigree(ctx context.Context, in *PedigreeRequest, opts ...grpc.CallOption) (*PedigreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PedigreeResponse)
	err := c.cc.Invoke(ctx, AgentSync_TracePedigree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) ProposeSwarmMutation(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, AgentSync_ProposeSwarmMutation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) QuerySwarmLedger(ctx context.Context, in *LedgerQueryRequest, opts ...grpc.CallOption) (*LedgerQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerQueryResponse)
	err := c.cc.Invoke(ctx, AgentSync_QuerySwarmLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) TimeTravelOverride(ctx context.Context, in *TimeTravelRequest, opts ...grpc.CallOption) (*TimeTravelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeTravelResponse)
	err := c.cc.Invoke(ctx, AgentSync_TimeTravelOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSyncClient) ForensicAudit(ctx context.Context, in *ForensicRequest, opts ...grpc.CallOption) (*ForensicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForensicResponse)
	err := c.cc.Invoke(ctx, AgentSync_ForensicAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentSyncServer is the server API for AgentSync service.
// All implementations must embed UnimplementedAgentSyncServer
// for forward compatibility.
type AgentSyncServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	SyncState(context.Context, *StatePayload) (*SyncAck, error)
	StreamInference(*InferenceRequest, grpc.ServerStreamingServer[InferenceChunk]) error
	RemoteExecute(context.Context, *CommandPayload) (*CommandResult, error)
	// User Maintenance & Synchronization RPCs
	CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*UserResponse, error)
	ManageGroup(context.Context, *ManageGroupRequest) (*UserResponse, error)
	ListUsers(context.Context, *UserDirectoryRequest) (*UserDirectoryResponse, error)
	SyncUsers(context.Context, *SyncUsersRequest) (*UserResponse, error)
	// Process & Port Monitoring RPCs
	GetProcessDirectory(context.Context, *ProcessDirectoryRequest) (*ProcessDirectoryResponse, error)
	GetPortBindings(context.Context, *PortBindingsRequest) (*PortBindingsResponse, error)
	// High-Speed Agent Migration (Virtual Travel) RPC
	TeleportAgent(context.Context, *TeleportRequest) (*TeleportResponse, error)
	// Agent Pedigree & 7-Layer Swarm Cooperation RPC
	TracePedigree(context.Context, *PedigreeRequest) (*PedigreeResponse, error)
	// Agent Ticketing, Relational Memory, and Immutable Ledger RPCs
	ProposeSwarmMutation(context.Context, *MutationRequest) (*MutationResponse, error)
	QuerySwarmLedger(context.Context, *LedgerQueryRequest) (*LedgerQueryResponse, error)
	// Jetweb Time Machine & Forensic Decision Accounting RPCs
	TimeTravelOverride(context.Context, *TimeTravelRequest) (*TimeTravelResponse, error)
	ForensicAudit(context.Context, *ForensicRequest) (*ForensicResponse, error)
	mustEmbedUnimplementedAgentSyncServer()
}

// UnimplementedAgentSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentSyncServer struct{}

func (UnimplementedAgentSyncServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentSyncServer) SyncState(context.Context, *StatePayload) (*SyncAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncState not implemented")
}
func (UnimplementedAgentSyncServer) StreamInference(*InferenceRequest, grpc.ServerStreamingServer[InferenceChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamInference not implemented")
}
func (UnimplementedAgentSyncServer) RemoteExecute(context.Context, *CommandPayload) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoteExecute not implemented")
}
func (UnimplementedAgentSyncServer) CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedAgentSyncServer) ChangePassword(context.Context, *ChangePasswordRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAgentSyncServer) ManageGroup(context.Context, *ManageGroupRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageGroup not implemented")
}
func (UnimplementedAgentSyncServer) ListUsers(context.Context, *UserDirectoryRequest) (*UserDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAgentSyncServer) SyncUsers(context.Context, *SyncUsersRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncUsers not implemented")
}
func (UnimplementedAgentSyncServer) GetProcessDirectory(context.Context, *ProcessDirectoryRequest) (*ProcessDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcessDirectory not implemented")
}
func (UnimplementedAgentSyncServer) GetPortBindings(context.Context, *PortBindingsRequest) (*PortBindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortBindings not implemented")
}
func (UnimplementedAgentSyncServer) TeleportAgent(context.Context, *TeleportRequest) (*TeleportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TeleportAgent not implemented")
}
func (UnimplementedAgentSyncServer) TracePedigree(context.Context, *PedigreeRequest) (*PedigreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TracePedigree not implemented")
}
func (UnimplementedAgentSyncServer) ProposeSwarmMutation(context.Context, *MutationRequest) (*MutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeSwarmMutation not implemented")
}
func (UnimplementedAgentSyncServer) QuerySwarmLedger(context.Context, *LedgerQueryRequest) (*LedgerQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuerySwarmLedger not implemented")
}
func (UnimplementedAgentSyncServer) TimeTravelOverride(context.Context, *TimeTravelRequest) (*TimeTravelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TimeTravelOverride not implemented")
}
func (UnimplementedAgentSyncServer) ForensicAudit(context.Context, *ForensicRequest) (*ForensicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForensicAudit not implemented")
}
func (UnimplementedAgentSyncServer) mustEmbedUnimplementedAgentSyncServer() {}
func (UnimplementedAgentSyncServer) testEmbeddedByValue()                   {}

// UnsafeAgentSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentSyncServer will
// result in compilation errors.
type UnsafeAgentSyncServer interface {
	mustEmbedUnimplementedAgentSyncServer()
}

func RegisterAgentSyncServer(s grpc.ServiceRegistrar, srv AgentSyncServer) {
	// If the following call panics, it indicates UnimplementedAgentSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentSync_ServiceDesc, srv)
}

func _AgentSync_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_SyncState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).SyncState(ctx, req.(*StatePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_StreamInference_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InferenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentSyncServer).StreamInference(m, &grpc.GenericServerStream[InferenceRequest, InferenceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentSync_StreamInferenceServer = grpc.ServerStreamingServer[InferenceChunk]

func _AgentSync_RemoteExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).RemoteExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_RemoteExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).RemoteExecute(ctx, req.(*CommandPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_ManageGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).ManageGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_ManageGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).ManageGroup(ctx, req.(*ManageGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).ListUsers(ctx, req.(*UserDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_SyncUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).SyncUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_SyncUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).SyncUsers(ctx, req.(*SyncUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_GetProcessDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).GetProcessDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_GetProcessDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).GetProcessDirectory(ctx, req.(*ProcessDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_GetPortBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).GetPortBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_GetPortBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).GetPortBindings(ctx, req.(*PortBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_TeleportAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeleportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).TeleportAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_TeleportAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).TeleportAgent(ctx, req.(*TeleportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_TracePedigree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PedigreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).TracePedigree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_TracePedigree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).TracePedigree(ctx, req.(*PedigreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_ProposeSwarmMutation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).ProposeSwarmMutation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_ProposeSwarmMutation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).ProposeSwarmMutation(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_QuerySwarmLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).QuerySwarmLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_QuerySwarmLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).QuerySwarmLedger(ctx, req.(*LedgerQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_TimeTravelOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeTravelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).TimeTravelOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_TimeTravelOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).TimeTravelOverride(ctx, req.(*TimeTravelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSync_ForensicAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForensicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSyncServer).ForensicAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSync_ForensicAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSyncServer).ForensicAudit(ctx, req.(*ForensicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentSync_ServiceDesc is the grpc.ServiceDesc for AgentSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentSync",
	HandlerType: (*AgentSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AgentSync_Ping_Handler,
		},
		{
			MethodName: "SyncState",
			Handler:    _AgentSync_SyncState_Handler,
		},
		{
			MethodName: "RemoteExecute",
			Handler:    _AgentSync_RemoteExecute_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AgentSync_CreateUser_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AgentSync_ChangePassword_Handler,
		},
		{
			MethodName: "ManageGroup",
			Handler:    _AgentSync_ManageGroup_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _AgentSync_ListUsers_Handler,
		},
		{
			MethodName: "SyncUsers",
			Handler:    _AgentSync_SyncUsers_Handler,
		},
		{
			MethodName: "GetProcessDirectory",
			Handler:    _AgentSync_GetProcessDirectory_Handler,
		},
		{
			MethodName: "GetPortBindings",
			Handler:    _AgentSync_GetPortBindings_Handler,
		},
		{
			MethodName: "TeleportAgent",
			Handler:    _AgentSync_TeleportAgent_Handler,
		},
		{
			MethodName: "TracePedigree",
			Handler:    _AgentSync_TracePedigree_Handler,
		},
		{
			MethodName: "ProposeSwarmMutation",
			Handler:    _AgentSync_ProposeSwarmMutation_Handler,
		},
		{
			MethodName: "QuerySwarmLedger",
			Handler:    _AgentSync_QuerySwarmLedger_Handler,
		},
		{
			MethodName: "TimeTravelOverride",
			Handler:    _AgentSync_TimeTravelOverride_Handler,
		},
		{
			MethodName: "ForensicAudit",
			Handler:    _AgentSync_ForensicAudit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInference",
			Handler:       _AgentSync_StreamInference_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sync.proto",
}

const (
	AgentToolUse_ExecuteFilesystem_FullMethodName  = "/proto.AgentToolUse/ExecuteFilesystem"
	AgentToolUse_ExecuteWebAccess_FullMethodName   = "/proto.AgentToolUse/ExecuteWebAccess"
	AgentToolUse_ExecuteWikipedia_FullMethodName   = "/proto.AgentToolUse/ExecuteWikipedia"
	AgentToolUse_ExecuteBrowserAuth_FullMethodName = "/proto.AgentToolUse/ExecuteBrowserAuth"
	AgentToolUse_ExecuteKeepAlive_FullMethodName   = "/proto.AgentToolUse/ExecuteKeepAlive"
)

// AgentToolUseClient is the client API for AgentToolUse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentToolUse Service for Native Tooling
type AgentToolUseClient interface {
	ExecuteFilesystem(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error)
	ExecuteWebAccess(ctx context.Context, in *WebAccessRequest, opts ...grpc.CallOption) (*WebAccessResponse, error)
	ExecuteWikipedia(ctx context.Context, in *WikipediaRequest, opts ...grpc.CallOption) (*WikipediaResponse, error)
	ExecuteBrowserAuth(ctx context.Context, in *BrowserAuthRequest, opts ...grpc.CallOption) (*BrowserAuthResponse, error)
	ExecuteKeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
}

type agentToolUseClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentToolUseClient(cc grpc.ClientConnInterface) AgentToolUseClient {
	return &agentToolUseClient{cc}
}

func (c *agentToolUseClient) ExecuteFilesystem(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilesystemResponse)
	err := c.cc.Invoke(ctx, AgentToolUse_ExecuteFilesystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentToolUseClient) ExecuteWebAccess(ctx context.Context, in *WebAccessRequest, opts ...grpc.CallOption) (*WebAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebAccessResponse)
	err := c.cc.Invoke(ctx, AgentToolUse_ExecuteWebAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentToolUseClient) ExecuteWikipedia(ctx context.Context, in *WikipediaRequest, opts ...grpc.CallOption) (*WikipediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WikipediaResponse)
	err := c.cc.Invoke(ctx, AgentToolUse_ExecuteWikipedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentToolUseClient) ExecuteBrowserAuth(ctx context.Context, in *BrowserAuthRequest, opts ...grpc.CallOption) (*BrowserAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowserAuthResponse)
	err := c.cc.Invoke(ctx, AgentToolUse_ExecuteBrowserAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentToolUseClient) ExecuteKeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, AgentToolUse_ExecuteKeepAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentToolUseServer is the server API for AgentToolUse service.
// All implementations must embed UnimplementedAgentToolUseServer
// for forward compatibility.
//
// AgentToolUse Service for Native Tooling
type AgentToolUseServer interface {
	ExecuteFilesystem(context.Context, *FilesystemRequest) (*FilesystemResponse, error)
	ExecuteWebAccess(context.Context, *WebAccessRequest) (*WebAccessResponse, error)
	ExecuteWikipedia(context.Context, *WikipediaRequest) (*WikipediaResponse, error)
	ExecuteBrowserAuth(context.Context, *BrowserAuthRequest) (*BrowserAuthResponse, error)
	ExecuteKeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	mustEmbedUnimplementedAgentToolUseServer()
}

// UnimplementedAgentToolUseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentToolUseServer struct{}

func (UnimplementedAgentToolUseServer) ExecuteFilesystem(context.Context, *FilesystemRequest) (*FilesystemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteFilesystem not implemented")
}
func (UnimplementedAgentToolUseServer) ExecuteWebAccess(context.Context, *WebAccessRequest) (*WebAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteWebAccess not implemented")
}
func (UnimplementedAgentToolUseServer) ExecuteWikipedia(context.Context, *WikipediaRequest) (*WikipediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteWikipedia not implemented")
}
func (UnimplementedAgentToolUseServer) ExecuteBrowserAuth(context.Context, *BrowserAuthRequest) (*BrowserAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteBrowserAuth not implemented")
}
func (UnimplementedAgentToolUseServer) ExecuteKeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteKeepAlive not implemented")
}
func (UnimplementedAgentToolUseServer) mustEmbedUnimplementedAgentToolUseServer() {}
func (UnimplementedAgentToolUseServer) testEmbeddedByValue()                      {}

// UnsafeAgentToolUseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentToolUseServer will
// result in compilation errors.
type UnsafeAgentToolUseServer interface {
	mustEmbedUnimplementedAgentToolUseServer()
}

func RegisterAgentToolUseServer(s grpc.ServiceRegistrar, srv AgentToolUseServer) {
	// If the following call panics, it indicates UnimplementedAgentToolUseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentToolUse_ServiceDesc, srv)
}

func _AgentToolUse_ExecuteFilesystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToolUseServer).ExecuteFilesystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentToolUse_ExecuteFilesystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToolUseServer).ExecuteFilesystem(ctx, req.(*FilesystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentToolUse_ExecuteWebAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToolUseServer).ExecuteWebAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentToolUse_ExecuteWebAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToolUseServer).ExecuteWebAccess(ctx, req.(*WebAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentToolUse_ExecuteWikipedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WikipediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToolUseServer).ExecuteWikipedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentToolUse_ExecuteWikipedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToolUseServer).ExecuteWikipedia(ctx, req.(*WikipediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentToolUse_ExecuteBrowserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowserAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToolUseServer).ExecuteBrowserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentToolUse_ExecuteBrowserAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToolUseServer).ExecuteBrowserAuth(ctx, req.(*BrowserAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentToolUse_ExecuteKeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToolUseServer).ExecuteKeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentToolUse_ExecuteKeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToolUseServer).ExecuteKeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentToolUse_ServiceDesc is the grpc.ServiceDesc for AgentToolUse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentToolUse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentToolUse",
	HandlerType: (*AgentToolUseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteFilesystem",
			Handler:    _AgentToolUse_ExecuteFilesystem_Handler,
		},
		{
			MethodName: "ExecuteWebAccess",
			Handler:    _AgentToolUse_ExecuteWebAccess_Handler,
		},
		{
			MethodName: "ExecuteWikipedia",
			Handler:    _AgentToolUse_ExecuteWikipedia_Handler,
		},
		{
			MethodName: "ExecuteBrowserAuth",
			Handler:    _AgentToolUse_ExecuteBrowserAuth_Handler,
		},
		{
			MethodName: "ExecuteKeepAlive",
			Handler:    _AgentToolUse_ExecuteKeepAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sync.proto",
}
